apiVersion: v1
kind: Service
metadata:
  name: nexus3-service
spec:
  type: LoadBalancer
  selector:
    app: nexus3
  ports:
  - name: nexus3-port
    port: 8080
    targetPort: 8080
    protocol: TCP
  